-- AI Spending Insights: curated, per-user observations generated by the
-- on-device detector swarm + server-side curator LLM
-- (docs/plans/2026-07-28-ai-spending-insights.md).
--
-- Owner-only RLS, matching `user_field_corrections` / `user_category_preferences`
-- — this is per-user generated content, not a shared cache.

create table if not exists public.spending_insights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  -- Closed vocabulary: spending_spike | category_shift | habit | streak | forecast
  insight_type text not null check (
    insight_type in (
      'spending_spike',
      'category_shift',
      'habit',
      'streak',
      'forecast'
    )
  ),
  -- Stable dedup key for the underlying fact (mirrors client InsightCandidate.factKey).
  fact_key text not null,
  -- Curator-rewritten user-facing sentence.
  body text not null,
  -- 0 = top-ranked in its generation cycle.
  rank int not null default 0 check (rank >= 0),
  dismissed boolean not null default false,
  -- Structured facts the curator was given (jsonb) — for debugging / audit,
  -- never shown raw to the user.
  facts jsonb,
  created_at timestamptz not null default now(),
  dismissed_at timestamptz
);

create index if not exists spending_insights_user_created_idx
  on public.spending_insights (user_id, created_at desc);

create index if not exists spending_insights_user_fact_key_idx
  on public.spending_insights (user_id, fact_key);

-- One active (non-dismissed) row per fact_key per user — a later cycle that
-- regenerates the same fact updates/replaces rather than stacking duplicates.
create unique index if not exists spending_insights_user_fact_active_uidx
  on public.spending_insights (user_id, fact_key)
  where dismissed = false;

alter table public.spending_insights enable row level security;

create policy "spending_insights_owner"
  on public.spending_insights
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
